# Generated by Django 4.1.7 on 2023-03-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Trip',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.AddField(
            model_name='experience',
            name='expenses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
