# Generated by Django 4.1.7 on 2023-03-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_experience_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('F', 'Flight'), ('R', 'Road Trip'), ('B', 'Bus')], default='F', max_length=1)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.experience')),
            ],
        ),
    ]
