# Generated by Django 4.1.7 on 2023-03-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_meal_feeding_transportation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='TRANSPORTATION',
            new_name='transportation',
        ),
    ]
