# Generated by Django 4.1.7 on 2023-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_trip_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('Date', models.DateField()),
                ('Trip', models.IntegerField(verbose_name=int)),
                ('Description', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
