# Generated by Django 4.1.7 on 2023-03-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='meal',
            new_name='TRANSPORTATION',
        ),
    ]
