# Generated by Django 4.1.7 on 2023-03-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_transportation_feeding_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='date',
            field=models.DateField(verbose_name='Experience Date'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='transportation',
            field=models.CharField(choices=[('F', 'Air'), ('R', 'Car'), ('B', 'Bus'), ('T', 'Train'), ('S', 'Ship'), ('B', 'Bicycle')], default='F', max_length=1),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
            ],
        ),
    ]
