# Generated by Django 4.1.7 on 2023-03-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_feeding_date_alter_feeding_transportation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
